# Generated by Django 4.0.4 on 2022-06-12 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delicious', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Dessert', 'Dessert'), ('Appetizers', 'Appetizers'), ('Drinks', 'Drinks'), ('Uncategorized', 'Uncategorized')], default='Uncategorized', max_length=13),
        ),
    ]
