# Generated by Django 4.0.4 on 2022-04-28 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delicious', '0002_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-published_on',)},
        ),
    ]
