# Generated by Django 4.0.4 on 2022-06-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delicious', '0002_alter_category_options_alter_category_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='is_cooked',
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Dinner', 'Dinner'), ('Dessert', 'Dessert'), ('Appetizers', 'Appetizers'), ('Drinks', 'Drinks'), ('Uncategorized', 'Uncategorized')], default='Uncategorized', max_length=20),
        ),
    ]
