# Generated by Django 4.0.4 on 2022-04-25 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delicious', '0002_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cooked',
            field=models.ManyToManyField(blank=True, related_name='cooked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_cooked',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='CookedRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delicious.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
