# Generated by Django 4.0.4 on 2022-04-26 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delicious', '0007_alter_recipe_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together=set(),
        ),
    ]
