# Generated by Django 4.0.4 on 2022-06-26 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliciousappuser',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
