# Generated by Django 4.0.4 on 2022-06-28 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_deliciousappuser_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliciousappuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
