# Generated by Django 4.0.4 on 2022-06-28 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_deliciousappuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliciousappuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
